# Generated by Django 5.2.15 on 2026-07-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='musteri_no',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
