# Generated by Django 5.2.15 on 2026-07-05 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IsKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep_no', models.CharField(max_length=50)),
                ('yapilan_is', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('devam_ediyor', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı')], max_length=20)),
                ('odenen_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('borc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_kayitlari', to='dashboard.musteri')),
            ],
        ),
    ]
