# Generated by Django 5.2.15 on 2026-07-05 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, choices=[('aylik', 'Aylık'), ('yillik', 'Yıllık')], max_length=20, null=True)),
                ('durum', models.CharField(choices=[('deneme', 'Deneme'), ('aktif', 'Aktif'), ('pasif', 'Pasif'), ('suresi_doldu', 'Süresi Doldu'), ('iptal', 'İptal')], default='deneme', max_length=20)),
                ('deneme_baslangic', models.DateTimeField(blank=True, null=True)),
                ('deneme_bitis', models.DateTimeField(blank=True, null=True)),
                ('mevcut_donem_baslangic', models.DateTimeField(blank=True, null=True)),
                ('mevcut_donem_bitis', models.DateTimeField(blank=True, null=True)),
                ('sonraki_odeme_tarihi', models.DateField(blank=True, null=True)),
                ('iptal_tarihi', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonelik', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OdemeKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odeme_yontemi', models.CharField(default='whatsapp_iban', max_length=20)),
                ('durum', models.CharField(choices=[('talep_edildi', 'Talep Edildi'), ('beklemede', 'Beklemede'), ('basarili', 'Başarılı'), ('basarisiz', 'Başarısız'), ('iade', 'İade')], default='talep_edildi', max_length=20)),
                ('dekont_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dekont_fotografi', models.ImageField(blank=True, null=True, upload_to='dekontlar/')),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True)),
                ('islem_tarihi', models.DateTimeField(auto_now_add=True)),
                ('onaylayan_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onaylanan_odemeler', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_odemeler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
