# Generated by Django 5.2.15 on 2026-07-05 15:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('yapilan_is', models.TextField()),
                ('ucret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('devam_ediyor', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı')], default='bekliyor', max_length=20)),
                ('odenen_tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('odeme_durumu', models.CharField(choices=[('odendi', 'Ödendi'), ('kismi_odendi', 'Kısmi Ödendi'), ('odenmedi', 'Ödenmedi')], default='odenmedi', editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_kayitlari', to='customers.musteri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_kayitlari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IsFotografi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='is_fotograflari/%Y/%m/%d/')),
                ('foto_tipi', models.CharField(choices=[('oncesi', 'Öncesi'), ('sonrasi', 'Sonrası'), ('teslim', 'Teslim'), ('ariza', 'Arıza'), ('diger', 'Diğer')], default='diger', max_length=20)),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('is_kaydi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='jobs.iskaydi')),
            ],
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_kaydi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ademeler', to='jobs.iskaydi')),
            ],
        ),
    ]
